# modules/30-security.sh
# Worker: System Users & Security Policy Controls

echo "👥 PHASE 3: System Users & Security Policy"
echo "----------------------------------------"

ensure_group() {
  g=$1
  if getent group "$g" >/dev/null 2>&1; then
    echo "group ok: $g"
    return 0
  fi
  if [ "$DRYRUN" -eq 1 ]; then
    echo "+ groupadd $g"
    return 0
  fi
  if have groupadd; then
    run_root groupadd "$g"
  elif have addgroup; then
    run_root addgroup "$g"
  else
    echo "$PROG: cannot create group $g" >&2
    return 1
  fi
}

ensure_user() {
  name=$1
  comment=${2:-"Stardust Operator"}
  if id "$name" >/dev/null 2>&1; then
    echo "user ok: $name"
  else
    if [ "$DRYRUN" -eq 1 ]; then
      echo "+ useradd -m -s /bin/bash -c '$comment' -G $GROUP $name"
    elif have adduser && [ "$PKG" = "apt" ]; then
      run_root adduser --disabled-password --gecos "$comment" --ingroup "$GROUP" "$name"
    elif have useradd; then
      run_root useradd -m -s /bin/bash -c "$comment" -G "$GROUP" "$name"
    elif have adduser; then
      run_root adduser -D -s /bin/ash -G "$GROUP" "$name"
    else
      echo "$PROG: cannot create user $name" >&2
      return 1
    fi
  fi

  if [ "$DRYRUN" -eq 1 ]; then
    echo "+ usermod -aG $GROUP $name"
    return 0
  fi

  if have usermod; then
    run_root usermod -aG "$GROUP" "$name" 2>/dev/null || true
  elif have adduser; then
    run_root adduser "$name" "$GROUP" 2>/dev/null || true
  fi

  home=$(getent passwd "$name" 2>/dev/null | cut -d: -f6)
  if [ -z "$home" ]; then
    home=/home/$name
  fi
  run_root mkdir -p "$home/.ssh"
  run_root chmod 0700 "$home/.ssh"
  run_root chown -R "$name:$name" "$home/.ssh"
  if [ ! -f "$home/.ssh/authorized_keys" ]; then
    if [ "$DRYRUN" -eq 0 ]; then
      as_root touch "$home/.ssh/authorized_keys"
      as_root chmod 0600 "$home/.ssh/authorized_keys"
      as_root chown "$name:$name" "$home/.ssh/authorized_keys"
    else
      echo "+ touch $home/.ssh/authorized_keys"
    fi
  fi
}

user_conf() {
  name=$1
  home=$(getent passwd "$name" 2>/dev/null | cut -d: -f6)
  if [ -z "$home" ]; then
    home=/home/$name
  fi
  dest=$home/.stardust.conf
  if [ -f "$dest" ]; then
    echo "conf exists: $dest (not overwritten)"
    return 0
  fi
  if [ "$DRYRUN" -eq 1 ]; then
    echo "+ write $dest"
    return 0
  fi
  as_root sh -c "cat > '$dest'" <<EOF
# Stardust config — generated by $PROG
# role=$ROLE host=$HOSTNAME os=$OS_ID pkg=$PKG init=$INIT user=$name

STARDUST_ROLE=$ROLE
STARDUST_ROOT=$STARDUST
PLATFORMS=$PLATFORMS
OWNER=$OWNER
ADMIN=$ADMIN
HUMAN=$HUMAN
DAEMON=$DAEMON
GROUP=$GROUP
DIR_MODE=0770
BEE=\$(command -v bee 2>/dev/null || echo $BEE_BIN)
APACHE_SERVICE=$SVC_APACHE
DB_SERVICE=$SVC_DB
APACHE_RELOAD="$RELOAD_APACHE"
DB_HOST=127.0.0.1
DB_PREFIX=bd_
EOF
  as_root chown "$name:$name" "$dest"
  as_root chmod 0600 "$dest"
  echo "wrote $dest"
}

# Execute profile security constraints
ensure_group "$GROUP"
ensure_group stardust
ensure_group adm
ensure_user "$OWNER" "Stardust code owner"
ensure_user "$ADMIN" "Stardust file admin"

write_sudoers /etc/sudoers.d/stardust-deploy <<EOF
# Stardust sudoers — deploy user
$OWNER ALL=(ALL) NOPASSWD: /usr/local/bin/stardust, /usr/local/bin/crdir, /usr/local/bin/newfeature, /usr/local/sbin/stardust-priv
EOF

write_sudoers /etc/sudoers.d/stardust-admin <<EOF
# Stardust sudoers — admin user
$ADMIN ALL=(ALL) NOPASSWD: /usr/local/bin/stardust, /usr/local/bin/crdir, /usr/local/bin/newfeature, /usr/local/sbin/stardust-priv
EOF

user_conf "$OWNER"
if [ "$OWNER" != "$ADMIN" ]; then
  user_conf "$ADMIN"
fi
if [ "$HUMAN" != "$OWNER" ] && [ "$HUMAN" != "$ADMIN" ]; then
  user_conf "$HUMAN"
fi
